[NoDelete]
interface B2_Base {
    [Value] static b2Version getVersion();
    static long getByteCount();
};

interface b2Version {
    attribute long major;
    attribute long minor;
    attribute long revision;
};