[NoDelete]
interface B2_Collision {
    [Value] static b2Manifold collideCircles([Const] b2Circle circleA, [Ref] b2Transform xfA, [Const] b2Circle circleB, [Ref] b2Transform xfB);
    [Value] static b2Manifold collideCapsuleAndCircle([Const] b2Capsule capsuleA, [Ref] b2Transform xfA, [Const] b2Circle circleB, [Ref] b2Transform xfB);
    [Value] static b2Manifold collideSegmentAndCircle([Const] b2Segment segmentA, [Ref] b2Transform xfA, [Const] b2Circle circleB, [Ref] b2Transform xfB);
    [Value] static b2Manifold collidePolygonAndCircle([Const] b2Polygon polygonA, [Ref] b2Transform xfA, [Const] b2Circle circleB, [Ref] b2Transform xfB);
    [Value] static b2Manifold collideCapsules([Const] b2Capsule capsuleA, [Ref] b2Transform xfA, [Const] b2Capsule capsuleB, [Ref] b2Transform xfB);
    [Value] static b2Manifold collideSegmentAndCapsule([Const] b2Segment segmentA, [Ref] b2Transform xfA, [Const] b2Capsule capsuleB, [Ref] b2Transform xfB);
    [Value] static b2Manifold collidePolygonAndCapsule([Const] b2Polygon polygonA, [Ref] b2Transform xfA, [Const] b2Capsule capsuleB, [Ref] b2Transform xfB);
    [Value] static b2Manifold collidePolygons([Const] b2Polygon polygonA, [Ref] b2Transform xfA, [Const] b2Polygon polygonB, [Ref] b2Transform xfB);
    [Value] static b2Manifold collideSegmentAndPolygon([Const] b2Segment segmentA, [Ref] b2Transform xfA, [Const] b2Polygon polygonB, [Ref] b2Transform xfB);
    [Value] static b2Manifold collideChainSegmentAndCircle([Const] b2ChainSegment segmentA, [Ref] b2Transform xfA, [Const] b2Circle circleB, [Ref] b2Transform xfB);
    [Value] static b2Manifold collideChainSegmentAndCapsule([Const] b2ChainSegment segmentA, [Ref] b2Transform xfA, [Const] b2Capsule capsuleB, [Ref] b2Transform xfB, b2SimplexCache cache);
    [Value] static b2Manifold collideChainSegmentAndPolygon([Const] b2ChainSegment segmentA, [Ref] b2Transform xfA, [Const] b2Polygon polygonB, [Ref] b2Transform xfB, b2SimplexCache cache);
};

[StackAllocatable]
interface b2ManifoldPoint {
    void b2ManifoldPoint();
    [Value] attribute b2Vec2 anchorA;
    [Value] attribute b2Vec2 anchorB;
    attribute unsigned short id;
    attribute float normalImpulse;
    attribute float normalVelocity;
    attribute boolean persisted;
    [Value] attribute b2Vec2 point;
    attribute float separation;
    attribute float tangentImpulse;
    attribute float totalNormalImpulse;
};

[StackAllocatable]
interface b2Manifold {
    void b2Manifold();
    [Value] attribute b2Vec2 normal;
    attribute long pointCount;
    [Value] attribute b2ManifoldPoint[] points;
    attribute float rollingImpulse;
};
