[NoDelete]
interface B2_CharacterMover {
    [Value] static b2PlaneSolverResult solvePlanes([Value] b2Vec2 targetDelta, b2CollisionPlaneArray planes);
    [Value] static b2Vec2 clipVector([Value] b2Vec2 vector, [Const] b2CollisionPlaneArray planes);
};

[StackAllocatable]
interface b2PlaneResult {
    void b2PlaneResult();
    attribute boolean hit;
    [Value] attribute b2Plane plane;
};

[StackAllocatable]
interface b2CollisionPlane {
    void b2CollisionPlane();
    attribute boolean clipVelocity;
    [Value] attribute b2Plane plane;
    attribute float push;
    attribute float pushLimit;
};

[StackAllocatable]
interface b2PlaneSolverResult {
    void b2PlaneSolverResult();
    attribute long iterationCount;
    [Value] attribute b2Vec2 translation;
};