[NoDelete]
interface B2_Joint {
    static void destroyJoint(unsigned long long jointId);
    static boolean isValid(unsigned long long jointId);
    static b2JointType getType(unsigned long long jointId);
    static unsigned long long getBodyA(unsigned long long jointId);
    static unsigned long long getBodyB(unsigned long long jointId);
    static unsigned long getWorld(unsigned long long jointId);
    [Value] static b2Vec2 getLocalAnchorA(unsigned long long jointId);
    [Value] static b2Vec2 getLocalAnchorB(unsigned long long jointId);
    static void setLocalAnchorA(unsigned long long jointId, [Value] b2Vec2 localAnchor);
    static void setLocalAnchorB(unsigned long long jointId, [Value] b2Vec2 localAnchor);
    static float getReferenceAngle(unsigned long long jointId);
    static void setReferenceAngle(unsigned long long jointId, float angleInRadians);
    static void setLocalAxisA(unsigned long long jointId, [Value] b2Vec2 localAxis);
    [Value] static b2Vec2 getLocalAxisA(unsigned long long jointId);
    static void setCollideConnected(unsigned long long jointId, boolean shouldCollide);
    static boolean getCollideConnected(unsigned long long jointId);
    static void setUserData(unsigned long long jointId, any userData);
    static any getUserData(unsigned long long jointId);
    static void wakeBodies(unsigned long long jointId);
    [Value] static b2Vec2 getConstraintForce(unsigned long long jointId);
    static float getConstraintTorque(unsigned long long jointId);
    static float getLinearSeparation(unsigned long long jointId);
    static float getAngularSeparation(unsigned long long jointId);
    static float getConstraintTuningHertz(unsigned long long jointId);
    static float getConstraintTuningDampingRatio(unsigned long long jointId);
    static void setConstraintTuning(unsigned long long jointId, float hertz, float dampingRatio);
};

[NoDelete]
interface B2_DistanceJoint {
    static unsigned long long createDistanceJoint(unsigned long long worldId, [Const] b2DistanceJointDef def);
    static void defaultDistanceJointDef([Ref] b2DistanceJointDef result);

    static void setLength(unsigned long long jointId, float length);
    static float getLength(unsigned long long jointId);
    static void enableSpring(unsigned long long jointId, boolean enableSpring);
    static boolean isSpringEnabled(unsigned long long jointId);
    static void setSpringHertz(unsigned long long jointId, float hertz);
    static void setSpringDampingRatio(unsigned long long jointId, float dampingRatio);
    static float getSpringHertz(unsigned long long jointId);
    static float getSpringDampingRatio(unsigned long long jointId);
    static void enableLimit(unsigned long long jointId, boolean enableLimit);
    static boolean isLimitEnabled(unsigned long long jointId);
    static void setLengthRange(unsigned long long jointId, float minLength, float maxLength);
    static float getMinLength(unsigned long long jointId);
    static float getMaxLength(unsigned long long jointId);
    static float getCurrentLength(unsigned long long jointId);
    static void enableMotor(unsigned long long jointId, boolean enableMotor);
    static boolean isMotorEnabled(unsigned long long jointId);
    static void setMotorSpeed(unsigned long long jointId, float motorSpeed);
    static float getMotorSpeed(unsigned long long jointId);
    static void setMaxMotorForce(unsigned long long jointId, float force);
    static float getMaxMotorForce(unsigned long long jointId);
    static float getMotorForce(unsigned long long jointId);
};

[StackAllocatable]
interface b2DistanceJointDef {
    void b2DistanceJointDef();
    [Value] attribute b2BodyId bodyIdA;
    [Value] attribute b2BodyId bodyIdB;
    attribute boolean collideConnected;
    attribute float dampingRatio;
    attribute boolean enableLimit;
    attribute boolean enableMotor;
    attribute boolean enableSpring;
    attribute float hertz;
    attribute long internalValue;
    attribute float length;
    [Value] attribute b2Vec2 localAnchorA;
    [Value] attribute b2Vec2 localAnchorB;
    attribute float maxLength;
    attribute float maxMotorForce;
    attribute float minLength;
    attribute float motorSpeed;
    attribute VoidPtr userData;
};

[NoDelete]
interface B2_FilterJoint {
    static unsigned long long createFilterJoint(unsigned long long worldId, [Const] b2FilterJointDef def);
    static void defaultFilterJointDef([Ref] b2FilterJointDef result);
};

[StackAllocatable]
interface b2FilterJointDef {
    void b2FilterJointDef();
    [Value] attribute b2BodyId bodyIdA;
    [Value] attribute b2BodyId bodyIdB;
    attribute VoidPtr userData;
};

[NoDelete]
interface B2_MotorJoint {
    static unsigned long long createMotorJoint(unsigned long long worldId, [Const] b2MotorJointDef def);
    static void defaultMotorJointDef([Ref] b2MotorJointDef result);

    static void setLinearOffset(unsigned long long jointId, [Value] b2Vec2 linearOffset);
    [Value] static b2Vec2 getLinearOffset(unsigned long long jointId);
    static void setAngularOffset(unsigned long long jointId, float angularOffset);
    static float getAngularOffset(unsigned long long jointId);
    static void setMaxForce(unsigned long long jointId, float maxForce);
    static float getMaxForce(unsigned long long jointId);
    static void setMaxTorque(unsigned long long jointId, float maxTorque);
    static float getMaxTorque(unsigned long long jointId);
    static void setCorrectionFactor(unsigned long long jointId, float correctionFactor);
    static float getCorrectionFactor(unsigned long long jointId);
};

[StackAllocatable]
interface b2MotorJointDef {
    void b2MotorJointDef();
    attribute float angularOffset;
    [Value] attribute b2BodyId bodyIdA;
    [Value] attribute b2BodyId bodyIdB;
    attribute boolean collideConnected;
    attribute float correctionFactor;
    attribute long internalValue;
    [Value] attribute b2Vec2 linearOffset;
    attribute float maxForce;
    attribute float maxTorque;
    attribute VoidPtr userData;
};

[NoDelete]
interface B2_MouseJoint {
    static unsigned long long createMouseJoint(unsigned long long worldId, [Const] b2MouseJointDef def);
    static void defaultMouseJointDef([Ref] b2MouseJointDef result);

    static void setTarget(unsigned long long jointId, [Value] b2Vec2 target);
    [Value] static b2Vec2 getTarget(unsigned long long jointId);
    static void setSpringHertz(unsigned long long jointId, float hertz);
    static float getSpringHertz(unsigned long long jointId);
    static void setSpringDampingRatio(unsigned long long jointId, float dampingRatio);
    static float getSpringDampingRatio(unsigned long long jointId);
    static void setMaxForce(unsigned long long jointId, float maxForce);
    static float getMaxForce(unsigned long long jointId);
};

[StackAllocatable]
interface b2MouseJointDef {
    void b2MouseJointDef();
    [Value] attribute b2BodyId bodyIdA;
    [Value] attribute b2BodyId bodyIdB;
    attribute boolean collideConnected;
    attribute float dampingRatio;
    attribute float hertz;
    attribute long internalValue;
    attribute float maxForce;
    [Value] attribute b2Vec2 target;
    attribute VoidPtr userData;
};

[NoDelete]
interface B2_PrismaticJoint {
    static unsigned long long createPrismaticJoint(unsigned long long worldId, [Const] b2PrismaticJointDef def);
    static void defaultPrismaticJointDef([Ref] b2PrismaticJointDef result);

    static void enableSpring(unsigned long long jointId, boolean enableSpring);
    static boolean isSpringEnabled(unsigned long long jointId);
    static void setSpringHertz(unsigned long long jointId, float hertz);
    static float getSpringHertz(unsigned long long jointId);
    static void setSpringDampingRatio(unsigned long long jointId, float dampingRatio);
    static float getSpringDampingRatio(unsigned long long jointId);
    static void setTargetTranslation(unsigned long long jointId, float translation);
    static float getTargetTranslation(unsigned long long jointId);
    static void enableLimit(unsigned long long jointId, boolean enableLimit);
    static boolean isLimitEnabled(unsigned long long jointId);
    static float getLowerLimit(unsigned long long jointId);
    static float getUpperLimit(unsigned long long jointId);
    static void setLimits(unsigned long long jointId, float lower, float upper);
    static void enableMotor(unsigned long long jointId, boolean enableMotor);
    static boolean isMotorEnabled(unsigned long long jointId);
    static void setMotorSpeed(unsigned long long jointId, float motorSpeed);
    static float getMotorSpeed(unsigned long long jointId);
    static void setMaxMotorForce(unsigned long long jointId, float force);
    static float getMaxMotorForce(unsigned long long jointId);
    static float getMotorForce(unsigned long long jointId);
    static float getTranslation(unsigned long long jointId);
    static float getSpeed(unsigned long long jointId);
};

[StackAllocatable]
interface b2PrismaticJointDef {
    void b2PrismaticJointDef();
    [Value] attribute b2BodyId bodyIdA;
    [Value] attribute b2BodyId bodyIdB;
    attribute boolean collideConnected;
    attribute float dampingRatio;
    attribute boolean enableLimit;
    attribute boolean enableMotor;
    attribute boolean enableSpring;
    attribute float hertz;
    attribute long internalValue;
    [Value] attribute b2Vec2 localAnchorA;
    [Value] attribute b2Vec2 localAnchorB;
    [Value] attribute b2Vec2 localAxisA;
    attribute float lowerTranslation;
    attribute float maxMotorForce;
    attribute float motorSpeed;
    attribute float referenceAngle;
    attribute float upperTranslation;
    attribute VoidPtr userData;
};

[NoDelete]
interface B2_RevoluteJoint {
    static unsigned long long createRevoluteJoint(unsigned long long worldId, [Const] b2RevoluteJointDef def);
    static void defaultRevoluteJointDef([Ref] b2RevoluteJointDef result);

    static void enableSpring(unsigned long long jointId, boolean enableSpring);
    static boolean isSpringEnabled(unsigned long long jointId);
    static void setSpringHertz(unsigned long long jointId, float hertz);
    static float getSpringHertz(unsigned long long jointId);
    static void setSpringDampingRatio(unsigned long long jointId, float dampingRatio);
    static float getSpringDampingRatio(unsigned long long jointId);
    static void setTargetAngle(unsigned long long jointId, float angle);
    static float getTargetAngle(unsigned long long jointId);
    static float getAngle(unsigned long long jointId);
    static void enableLimit(unsigned long long jointId, boolean enableLimit);
    static boolean isLimitEnabled(unsigned long long jointId);
    static float getLowerLimit(unsigned long long jointId);
    static float getUpperLimit(unsigned long long jointId);
    static void setLimits(unsigned long long jointId, float lower, float upper);
    static void enableMotor(unsigned long long jointId, boolean enableMotor);
    static boolean isMotorEnabled(unsigned long long jointId);
    static void setMotorSpeed(unsigned long long jointId, float motorSpeed);
    static float getMotorSpeed(unsigned long long jointId);
    static float getMotorTorque(unsigned long long jointId);
    static void setMaxMotorTorque(unsigned long long jointId, float torque);
    static float getMaxMotorTorque(unsigned long long jointId);
};

[StackAllocatable]
interface b2RevoluteJointDef {
    void b2RevoluteJointDef();
    [Value] attribute b2BodyId bodyIdA;
    [Value] attribute b2BodyId bodyIdB;
    attribute boolean collideConnected;
    attribute float dampingRatio;
    attribute float drawSize;
    attribute boolean enableLimit;
    attribute boolean enableMotor;
    attribute boolean enableSpring;
    attribute float hertz;
    attribute long internalValue;
    [Value] attribute b2Vec2 localAnchorA;
    [Value] attribute b2Vec2 localAnchorB;
    attribute float lowerAngle;
    attribute float maxMotorTorque;
    attribute float motorSpeed;
    attribute float referenceAngle;
    attribute float upperAngle;
    attribute VoidPtr userData;
};

[NoDelete]
interface B2_WeldJoint {
    static unsigned long long createWeldJoint(unsigned long long worldId, [Const] b2WeldJointDef def);
    static void defaultWeldJointDef([Ref] b2WeldJointDef result);

    static void setLinearHertz(unsigned long long jointId, float hertz);
    static float getLinearHertz(unsigned long long jointId);
    static void setLinearDampingRatio(unsigned long long jointId, float dampingRatio);
    static float getLinearDampingRatio(unsigned long long jointId);
    static void setAngularHertz(unsigned long long jointId, float hertz);
    static float getAngularHertz(unsigned long long jointId);
    static void setAngularDampingRatio(unsigned long long jointId, float dampingRatio);
    static float getAngularDampingRatio(unsigned long long jointId);
};

[StackAllocatable]
interface b2WeldJointDef {
    void b2WeldJointDef();
    attribute float angularDampingRatio;
    attribute float angularHertz;
    [Value] attribute b2BodyId bodyIdA;
    [Value] attribute b2BodyId bodyIdB;
    attribute boolean collideConnected;
    attribute long internalValue;
    attribute float linearDampingRatio;
    attribute float linearHertz;
    [Value] attribute b2Vec2 localAnchorA;
    [Value] attribute b2Vec2 localAnchorB;
    attribute float referenceAngle;
    attribute VoidPtr userData;
};

[NoDelete]
interface B2_WheelJoint {
    static unsigned long long createWheelJoint(unsigned long long worldId, [Const] b2WheelJointDef def);
    static void defaultWheelJointDef([Ref] b2WheelJointDef result);

    static void enableSpring(unsigned long long jointId, boolean enableSpring);
    static boolean isSpringEnabled(unsigned long long jointId);
    static void setSpringHertz(unsigned long long jointId, float hertz);
    static float getSpringHertz(unsigned long long jointId);
    static void setSpringDampingRatio(unsigned long long jointId, float dampingRatio);
    static float getSpringDampingRatio(unsigned long long jointId);
    static void enableLimit(unsigned long long jointId, boolean enableLimit);
    static boolean isLimitEnabled(unsigned long long jointId);
    static float getLowerLimit(unsigned long long jointId);
    static float getUpperLimit(unsigned long long jointId);
    static void setLimits(unsigned long long jointId, float lower, float upper);
    static void enableMotor(unsigned long long jointId, boolean enableMotor);
    static boolean isMotorEnabled(unsigned long long jointId);
    static void setMotorSpeed(unsigned long long jointId, float motorSpeed);
    static float getMotorSpeed(unsigned long long jointId);
    static void setMaxMotorTorque(unsigned long long jointId, float torque);
    static float getMaxMotorTorque(unsigned long long jointId);
    static float getMotorTorque(unsigned long long jointId);
};

[StackAllocatable]
interface b2WheelJointDef {
    void b2WheelJointDef();
    [Value] attribute b2BodyId bodyIdA;
    [Value] attribute b2BodyId bodyIdB;
    attribute boolean collideConnected;
    attribute float dampingRatio;
    attribute boolean enableLimit;
    attribute boolean enableMotor;
    attribute boolean enableSpring;
    attribute float hertz;
    attribute long internalValue;
    [Value] attribute b2Vec2 localAnchorA;
    [Value] attribute b2Vec2 localAnchorB;
    [Value] attribute b2Vec2 localAxisA;
    attribute float lowerTranslation;
    attribute float maxMotorTorque;
    attribute float motorSpeed;
    attribute float upperTranslation;
    attribute VoidPtr userData;
};

enum b2JointType {
    "b2_distanceJoint",
    "b2_filterJoint",
    "b2_motorJoint",
    "b2_mouseJoint",
    "b2_prismaticJoint",
    "b2_revoluteJoint",
    "b2_weldJoint",
    "b2_wheelJoint"
};